
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQXVZNnA5YmllY0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1UZ3hPVEUxTVRsYUZ3MHpOVEV5TVRZeE9USXdNVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMyMENTK3Rsdm5xYWFYT00wQ0t3ai9odlpycXRicmF3bmpVV1hvbVc0UHZENXM5VVBjN21hcEltSTIKQ3JkVXJJY3BCT0llTEN5bEEva0hwOFFqRjgzcGJ0aUZIY2JqNGppV2d3T3g2aGxKZ0hTMUVrOGJUU1VybXRWNApzUlFBamxKTnJlLzlyRzZLQTlLMjdSSVpZTmk4SHMyWnROanVUN04rUE0xQUZjUXFJRThpVkgwZG93Ty9Tekx4Ci9ZczV0Y0NDUHExYmJ4cXVMKzRmaWJCZEFLVE5wTGNrMVVPa1NXOXZHSUZocXdXeXJyaUhzNnNPUTJra1V0MmEKOS8wY2ZadXIydGN5aWdQMERETmZqdTFnRVJiWjBpcUFBT0w2MC9tUG82Y1h6NHNHYzlKdkJGK3BzZDZaSkpmZAp4MVpySzdqTTh0a3pITWNPMEc4TXNqWlBXOUYzQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRTVZaZzVubWIvRHBwbUNaVTdHcUlkUzJDaUV6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3RiekJqMGxnUQptSzBRZVdaWnFTN2NBQ0VxaVZib2Iwb1haNzhrODg2blhKaGNpelFLcjJORDg4MWpaVW5GOWduQmxQZk0zcGViCkxGUEFsQWVCU2xwd3RKdWY2akRSdERiRTFkMkpsRXJmSXcrRXFKVDczQU0rWlVreG40dlNpdmZtVjBxNldqYXkKb2hEc3Mxbm14Z2F6eHZMV20xNWtjQ2V1T3ZJZDZtaGFBZ240Wjd0cVlQb1k2cjhIOERxb0ZjQjltaGNVTzRaTgowNHk4blQrYWd1UDVNUjh2MnBvU3JJUUZ1eHprdzFjWTRiODh3TlRRc01yVDFHVnVoS2U3U2EyU1VqTXBXb2JBCkVFYjlPdlp0bFNpNjcrQnNLenluUk41VThSbHAyeUx5N1ozRFliME9meFlEeGNjSDIvTFV4T2pMWnNsQnNLVnEKb1VnamJlTC9OU01rCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://43ae6ca7-3c5a-42ba-b440-2e86a6083cf2.ca-central-1-gw.linodelke.net:443
  name: lke548186

users:
- name: lke548186-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InNES0VDLVBMWktOQWRRaHc4eWZGenkxXzh1VUdzOUVub0Yxbi1qMkhYWTgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4teHg3aG4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZWZhYmY0OGMtNzY4Ny00NGRkLWI5ZjktY2I1ZGRiOWRlMTkzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Q26JlCSCtiBp2ET4fBSjqo1CWyKKTjzJZmImu3X818vHx-tjiRs_O4ilAax6liLmKVwx7uuGwJRBFciH0iwWxy_-2aJSqxnOTWoJYuNtauwEzmqrjB31wvgX2g63nptdSgdGj0CV_BA5CPWGjSDzAqv7Y4CCAI2Ao6-w5L7uNsh0L669fHmgAGcK4GEbL1VBrvzi7pJ9Nw8pm6EOXilAPFEvwfp5c1SOWdeM4Noyjp3qjVCdmmA-6zsQdSFwdZbC5s7yXLaXgNCVu8AWYtFnFP40wei6amaNqgCW7H1I3NySBFZhduYiY06gQ2QtYZ8Kql6qwipSQlGsQUrDP7gujw

contexts:
- context:
    cluster: lke548186
    namespace: default
    user: lke548186-admin
  name: lke548186-ctx

current-context: lke548186-ctx
